Add Ubuntu 24.04 and macOS 13
This required removing Python 3.7 which was EOL'd in 2023, as it's no longer
available in newer OS versions:

> Error: The version '3.7' with architecture 'x64' was not found for Ubuntu
> 24.04. The list of all available versions can be found here:
> https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

Python 3.7 EOL as of 2023-06-27:

* https://devguide.python.org/versions/
* https://peps.python.org/pep-0537/